### ISSUE TITLE
Mapper Implementation

### ISSUE THREAD

**Issue by alphitardian** [agushery/Movies#1]
https://github.com/agushery/Movies/blob/dfde0ac9a30e0dd3789400f372f430945ad00a3a/Movies/Core/Util/Mapper/MovieMapper.swift#L15

If you want to add a mapper class outside the model then better use a generic mapper. If not, I think it's better to add model mapping inside the model itself (e.g.: create an extension for that model).

**Comment by agushery** [comment]
Thank you for your advice, i will implement in future. But now i have to split it for more readable response to domains.
